[package]
name = "nitroid-virtualization"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
nitroid-core = { path = "../core" }
nitroid-iso9660 = { path = "../iso9660" }
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = "0.9"
kvm-ioctls = "0.18"
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Hypervisor",
    "Win32_System_Threading",
    "Win32_System_Memory",
] }
